# Cross-compile Windows binaries from Linux/WSL2 with MinGW-w64.
set(CMAKE_SYSTEM_NAME Windows)

set(MINGW_TRIPLET "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 compiler triplet")
if(MINGW_TRIPLET MATCHES "^i686-")
    set(CMAKE_SYSTEM_PROCESSOR x86)
else()
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
endif()

set(CMAKE_C_COMPILER "${MINGW_TRIPLET}-gcc")
set(CMAKE_CXX_COMPILER "${MINGW_TRIPLET}-g++")
set(CMAKE_RC_COMPILER "${MINGW_TRIPLET}-windres")
set(CMAKE_AR "${MINGW_TRIPLET}-ar")
set(CMAKE_RANLIB "${MINGW_TRIPLET}-ranlib")
set(CMAKE_STRIP "${MINGW_TRIPLET}-strip")
set(CMAKE_DLLTOOL "${MINGW_TRIPLET}-dlltool")

list(PREPEND CMAKE_FIND_ROOT_PATH
    "${CMAKE_INSTALL_PREFIX}"
    "/usr/${MINGW_TRIPLET}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

